version: '3.8'

services:
  mssql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql-server-2022
    hostname: mssql-server
    restart: unless-stopped
    
    environment:
      # Accept the End User License Agreement (required)
      - ACCEPT_EULA=Y
      
      # SQL Server System Administrator (SA) password
      # This is the default username for SQL Server
      - SA_PASSWORD=${SA_PASSWORD:-YourStrong@Password123}
      
      # SQL Server Product ID (optional)
      # Options: Developer (free, full features), Express (free, limited), Standard, Enterprise, EnterpriseCore
      - MSSQL_PID=${MSSQL_PID:-Developer}
      
      # Enable SQL Server Agent (optional, for scheduled jobs)
      - MSSQL_AGENT_ENABLED=${MSSQL_AGENT_ENABLED:-true}
      
      # Timezone (optional)
      - TZ=${TZ:-UTC}
    
    ports:
      # Map container port 1433 to host port 1433
      # Format: "host_port:container_port"
      - "${MSSQL_PORT:-1433}:1433"
    
    volumes:
      # Persist database data
      - mssql_data:/var/opt/mssql
      # Optional: Mount custom SQL scripts to initialize database
      # - ./init-scripts:/docker-entrypoint-initdb.d
    
    networks:
      - mssql-network
    
    # Resource limits (optional but recommended)
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 4G
        reservations:
          cpus: '1.0'
          memory: 2G
    
    # Health check to ensure container is ready
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P ${SA_PASSWORD:-YourStrong@Password123} -Q "SELECT 1" || exit 1
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  postgres:
    image: postgres:18-alpine
    container_name: postgres-server
    hostname: postgres-server
    restart: unless-stopped
    
    environment:
      # PostgreSQL superuser password
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      
      # PostgreSQL superuser name (default: postgres)
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      
      # Default database name (optional)
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
      
      # Timezone (optional)
      - TZ=${TZ:-UTC}
      
      # PostgreSQL configuration (optional)
      # Enable logging for better debugging
      - POSTGRES_INITDB_ARGS=--encoding=UTF8 --locale=C
    
    ports:
      # Map container port 5432 to host port 5432
      # Format: "host_port:container_port"
      - "${POSTGRES_PORT:-5432}:5432"
    
    volumes:
      # Persist database data
      - postgres_data:/var/lib/postgresql/data
      # Optional: Mount custom SQL scripts to initialize database
      # - ./postgres-init-scripts:/docker-entrypoint-initdb.d
    
    networks:
      - postgres-network
    
    # Resource limits (optional but recommended)
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 4G
        reservations:
          cpus: '1.0'
          memory: 2G
    
    # Health check to ensure container is ready
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  mssql_data:
    driver: local
    name: mssql_data
  postgres_data:
    driver: local
    name: postgres_data

networks:
  mssql-network:
    driver: bridge
    name: mssql-network
  postgres-network:
    driver: bridge
    name: postgres-network

